Updated Makefile to handle errors when fetching the latest version tag from Docker Hub.

diff --git a/openfaas/Makefile b/openfaas/Makefile
--- a/openfaas/Makefile
+++ b/openfaas/Makefile
@@ -16,12 +16,16 @@ build:
 	# Ensure the container is removed even if it doesn't exist
 	-docker container rm -f $(TEST_CONTAINER)
 	# Fetch the latest version tag from Docker Hub using the official Docker Hub API
-	LATEST_VERSION=$$(curl -s -H "Authorization: Bearer $TOKEN" "https://hub.docker.com/v2/repositories/$(IMAGE_NAME)/tags/?page_size=100&page=1&ordering=last_updated" | jq -r '.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name' | head -n 1)
-	LATEST_VERSION=$$(curl -s -H "Authorization: Bearer $TOKEN" "https://hub.docker.com/v2/repositories/$(IMAGE_NAME)/tags/?page_size=100&page=1&ordering=last_updated" | jq -r '.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name' | head -n 1)
+	LATEST_VERSION=$$(curl -s "https://hub.docker.com/v2/repositories/$(IMAGE_NAME)/tags/?page_size=100&page=1&ordering=last_updated" | jq -r '.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name' | head -n 1)
 	# Increment the latest version by one
 	NEW_VERSION=$$(echo $$LATEST_VERSION | awk -F. '{$$NF = $$NF + 1;} 1' | sed 's/ /./g')
 	# Update the VERSION file with the new version
 	echo $$NEW_VERSION > $(VERSION_FILE)
+	# Check if NEW_VERSION is not empty, then proceed
+	if [ -z "$$NEW_VERSION" ]; then \
+		echo "Error: Unable to get the latest version tag from Docker Hub."; \
+		exit 1; \
+	fi
 	# Run image for testing with platform specification
 	if [ -n "$$NEW_VERSION" ]; then \
 		docker run -d --name $(TEST_CONTAINER) --platform linux/amd64 -p 8080:8080 $(IMAGE_NAME):$$NEW_VERSION; \
