Update README.md (#2)
* Update README.md

Add CI status badge

* Update main.yaml

Move to current workflow

* Update version number -

* Update main.yaml

* Update version number -

---------

Co-authored-by: GitHub Action <action@github.com>

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -22,21 +22,29 @@ name: CI
 on:
   # Triggers the workflow on push or pull request events but only for the main
   # branch and not for VERSION file changes
-  push:
-    branches: [ main ]
-    paths-ignore: [ "VERSION", "fission/" ]
+  push: 
+    branches:
+      - '*'
+    paths:
+      - '**'
   pull_request:
-    branches: [ main ]
+    branches:
+      - main
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# This workflow contains a job called "build-test" and "build-production"
 jobs:
-  # This workflow contains a job called "build-test" and "build-production"
   build-test:
+    if: (github.event_name == 'push' && github.ref != 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'workflow_dispatch')
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    # Removed incorrect env variable reference
+    env:
+      BRANCH: ${{ github.ref }}
+      GITHUB_USERNAME: ${{ github.actor }}
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -49,17 +57,17 @@ jobs:
           python-version: 3.x
       
       # Install dependencies
-      - name: Install dependencies
+      - name: "Install dependencies"
         run: |
           python -m pip install --upgrade pip
           make check-packages
       
       # Increment the version number in the VERSION file and set the VERSION
       # environment variable
-      - name: Increment version number
+      - name: "Increment version number"
         run: |
           make update-version
-          export VERSION=$(cat VERSION)
+          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
 
       # Builds the package and runs tests
       - name: Build and test
@@ -72,18 +80,54 @@ jobs:
       # If tests pass, push the package to TestPyPI
       - name: Push to TestPyPI
         run: |
-          make upload-test TEST_PYPI_USER_AGENT=${{ secrets.TEST_PYPI_USER_AGENT }}
+          make upload-test TEST_PYPI_USER_AGENT=${{ secrets.TEST_PYPI_USER_AGENT }} || echo "Push to TestPyPI failed, but the workflow continues."
 
       # Pull the package from TestPyPI and run tests
-      - name: Pull from TestPyPI and test
+      #- name: Pull from TestPyPI and test
+      #  run: |
+      #    pip install --index-url https://test.pypi.org/simple/ klingon-serial
+      #    python -m pytest -v tests/  
+
+  increment-version:
+    runs-on: ubuntu-latest
+    # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
+    if: github.event_name == 'push' && github.ref != 'refs/heads/main'
+    needs: [build-test]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Increment version
         run: |
-          pip install --index-url https://test.pypi.org/simple/ klingon-serial
-          python -m unittest discover
+          file="VERSION"
+          if [ ! -f "$file" ]; then
+            echo "VERSION file does not exist. Creating with initial value 0.0.0."
+            echo "0.0.0" > "$file"
+          fi
+          
+          version=$(cat ${file})
+          IFS='.' read -ra VER <<< "$version"
+          ((VER[2]++))
+          new_version="${VER[0]}.${VER[1]}.${VER[2]}"
+          echo $new_version > $file
+          echo "New version: $new_version"
+
+      - name: Commit and push if necessary
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+          git add VERSION
+          git commit -m "Update version number - $new_version" -a || echo "No changes to commit"
+          git push
 
   build-production:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-    needs: build-test
+    # Removed incorrect env variable reference
+    env:
+      BRANCH: ${{ github.ref }}
+      GITHUB_USERNAME: ${{ github.actor }}
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -101,12 +145,11 @@ jobs:
           python -m pip install --upgrade pip
           make check-packages
       
-      # Increment the version number in the VERSION file and set the VERSION
+      # Get the version number in the VERSION file and set the VERSION
       # environment variable
-      - name: Increment version number
+      - name: "Get version number"
         run: |
-          make update-version
-          export VERSION=$(cat VERSION)
+          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
 
       # Builds the package and runs tests
       - name: Build and test
@@ -125,7 +168,7 @@ jobs:
       - name: Pull from PyPI and test
         run: |
           pip install klingon-serial
-          python -m unittest discover
+          python -m pytest -v tests/  
 
       # If uploads are successful, and the VERSION file has changed push the
       # updated VERSION file back to the repository
@@ -133,4 +176,4 @@ jobs:
         run: |
           git config --global user.name 'GitHub Actions'
           git config --global user.email 'github-actions@github.com'
-          git diff --quiet VERSION || (git add VERSION && git commit -m "Update version number - $VERSION" && git push) || echo "VERSION file not updated"
+          git diff --quiet VERSION || (git add VERSION && git commit -m "Update version number - ${{ env.VERSION }}" && git push) || echo "VERSION file not updated"
